### ISSUE TITLE
Rename main branch name

### ISSUE THREAD

**Issue by cyyynthia** [uuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuu/uuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuu#13]
The branch name is still default and boring "master", and should be renamed to uuuuuuuuuuuuuuu to enhance the repo's quality

**Comment by AlexFlipnote** [comment]
u

**Comment by Soheab** [comment]
u

**Comment by Cynosphere** [comment]
u

**Comment by NotNite** [comment]
I don't think you can change the branch name via the GitHub web UI, and I literally can't clone this repo to my PC.

**Comment by cyyynthia** [comment]
A workaround could be creating a new branch called uuuuuu on GitHub (which will have the same history as master), then setting it as default branch and deleting the boring master branch

**Comment by NotNite** [comment]
Fixed.
